// Code generated by entc, DO NOT EDIT.

package session

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdleTimeExpiredAt holds the string denoting the idletimeexpiredat field in the database.
	FieldIdleTimeExpiredAt = "idle_time_expired_at"
	// FieldLifeTimeExpiredAt holds the string denoting the lifetimeexpiredat field in the database.
	FieldLifeTimeExpiredAt = "life_time_expired_at"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the session in the database.
	Table = "sessions"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "sessions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_sessions"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldIdleTimeExpiredAt,
	FieldLifeTimeExpiredAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Session type.
var ForeignKeys = []string{
	"user_sessions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
