// Code generated by entc, DO NOT EDIT.

package session

import (
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/masseelch/go-api-skeleton/ent/predicate"
	go_token "github.com/masseelch/go-token"
)

// ID filters vertices based on their identifier.
func ID(id go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id go_token.Token) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// IdleTimeExpiredAt applies equality check predicate on the "idleTimeExpiredAt" field. It's identical to IdleTimeExpiredAtEQ.
func IdleTimeExpiredAt(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIdleTimeExpiredAt), v))
	})
}

// LifeTimeExpiredAt applies equality check predicate on the "lifeTimeExpiredAt" field. It's identical to LifeTimeExpiredAtEQ.
func LifeTimeExpiredAt(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLifeTimeExpiredAt), v))
	})
}

// IdleTimeExpiredAtEQ applies the EQ predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtEQ(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIdleTimeExpiredAt), v))
	})
}

// IdleTimeExpiredAtNEQ applies the NEQ predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIdleTimeExpiredAt), v))
	})
}

// IdleTimeExpiredAtIn applies the In predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtIn(vs ...time.Time) predicate.Session {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Session(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldIdleTimeExpiredAt), v...))
	})
}

// IdleTimeExpiredAtNotIn applies the NotIn predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtNotIn(vs ...time.Time) predicate.Session {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Session(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldIdleTimeExpiredAt), v...))
	})
}

// IdleTimeExpiredAtGT applies the GT predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtGT(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIdleTimeExpiredAt), v))
	})
}

// IdleTimeExpiredAtGTE applies the GTE predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtGTE(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIdleTimeExpiredAt), v))
	})
}

// IdleTimeExpiredAtLT applies the LT predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtLT(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIdleTimeExpiredAt), v))
	})
}

// IdleTimeExpiredAtLTE applies the LTE predicate on the "idleTimeExpiredAt" field.
func IdleTimeExpiredAtLTE(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIdleTimeExpiredAt), v))
	})
}

// LifeTimeExpiredAtEQ applies the EQ predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtEQ(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLifeTimeExpiredAt), v))
	})
}

// LifeTimeExpiredAtNEQ applies the NEQ predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLifeTimeExpiredAt), v))
	})
}

// LifeTimeExpiredAtIn applies the In predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtIn(vs ...time.Time) predicate.Session {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Session(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLifeTimeExpiredAt), v...))
	})
}

// LifeTimeExpiredAtNotIn applies the NotIn predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtNotIn(vs ...time.Time) predicate.Session {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Session(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLifeTimeExpiredAt), v...))
	})
}

// LifeTimeExpiredAtGT applies the GT predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtGT(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLifeTimeExpiredAt), v))
	})
}

// LifeTimeExpiredAtGTE applies the GTE predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtGTE(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLifeTimeExpiredAt), v))
	})
}

// LifeTimeExpiredAtLT applies the LT predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtLT(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLifeTimeExpiredAt), v))
	})
}

// LifeTimeExpiredAtLTE applies the LTE predicate on the "lifeTimeExpiredAt" field.
func LifeTimeExpiredAtLTE(v time.Time) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLifeTimeExpiredAt), v))
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		p(s.Not())
	})
}
