// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/masseelch/go-api-skeleton/ent/runtime.go

const (
	Version = "v0.5.1-0.20201107165150-d993b59d9045"            // Version of ent codegen.
	Sum     = "h1:QiMJH4nnnXv+sB539NOoNNO3Qky+aOKpnCF/WTNIn+k=" // Sum of ent codegen.
)
