// Code generated by entc, DO NOT EDIT.

package handler

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-playground/validator/v10"
	"github.com/sirupsen/logrus"

	"github.com/masseelch/go-api-skeleton/ent"
)

type JobHandler struct {
	r *chi.Mux

	client    *ent.Client
	validator *validator.Validate
	logger    *logrus.Logger
}

func NewJobHandler(c *ent.Client, v *validator.Validate, log *logrus.Logger) *JobHandler {
	h := &JobHandler{
		r:         chi.NewRouter(),
		client:    c,
		validator: v,
		logger:    log,
	}

	h.r.Get("/{id:\\d+}", h.read)

	return h
}

func (h JobHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.r.ServeHTTP(w, r)
}

type UserHandler struct {
	r *chi.Mux

	client    *ent.Client
	validator *validator.Validate
	logger    *logrus.Logger
}

func NewUserHandler(c *ent.Client, v *validator.Validate, log *logrus.Logger) *UserHandler {
	h := &UserHandler{
		r:         chi.NewRouter(),
		client:    c,
		validator: v,
		logger:    log,
	}

	h.r.Get("/{id:\\d+}", h.read)

	return h
}

func (h UserHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.r.ServeHTTP(w, r)
}
