// Code generated by entc, DO NOT EDIT.

package handler

import (
	"net/http"
	"strconv"

	"github.com/go-chi/chi"
	"github.com/masseelch/render"

	"github.com/masseelch/go-api-skeleton/ent"
	"github.com/masseelch/go-api-skeleton/ent/job"
	"github.com/masseelch/go-api-skeleton/ent/session"
	"github.com/masseelch/go-api-skeleton/ent/user"

	go_token "github.com/masseelch/go-token"
)

// This function fetches the Job model identified by a give url-parameter from
// database and returns it to the client.
func (h JobHandler) read(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	e, err := h.client.Job.Query().Where(job.ID(id)).WithUsers().Only(r.Context())
	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).Error("unexpected")                   // todo - better error
			render.InternalServerError(w, r, "unexpected error occurred") // todo - better error
			return
		default:
			h.logger.WithError(err).Error("logic") // todo - better stuff here pls
			render.InternalServerError(w, r, "logic")
			return
		}
	}

	h.logger.WithField("job", e.ID).Info("job rendered") // todo - better stuff here pls
	render.OK(w, r, e)
}

// This function fetches the Session model identified by a give url-parameter from
// database and returns it to the client.
func (h SessionHandler) read(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id := go_token.Token(idp)

	e, err := h.client.Session.Query().Where(session.ID(id)).Only(r.Context())
	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).Error("unexpected")                   // todo - better error
			render.InternalServerError(w, r, "unexpected error occurred") // todo - better error
			return
		default:
			h.logger.WithError(err).Error("logic") // todo - better stuff here pls
			render.InternalServerError(w, r, "logic")
			return
		}
	}

	h.logger.WithField("job", e.ID).Info("job rendered") // todo - better stuff here pls
	render.OK(w, r, e)
}

// This function fetches the User model identified by a give url-parameter from
// database and returns it to the client.
func (h UserHandler) read(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	e, err := h.client.User.Query().Where(user.ID(id)).Only(r.Context())
	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).Error("unexpected")                   // todo - better error
			render.InternalServerError(w, r, "unexpected error occurred") // todo - better error
			return
		default:
			h.logger.WithError(err).Error("logic") // todo - better stuff here pls
			render.InternalServerError(w, r, "logic")
			return
		}
	}

	h.logger.WithField("job", e.ID).Info("job rendered") // todo - better stuff here pls
	render.OK(w, r, e)
}
