// Code generated by entc, DO NOT EDIT.

package ent

func (j *JobCreate) SetJob(input *Job) *JobCreate {
	j.SetDate(input.Date)
	j.SetTask(input.Task)
	j.SetState(input.State)
	j.SetReport(input.Report)
	j.SetRest(input.Rest)
	j.SetNote(input.Note)
	j.SetCustomerName(input.CustomerName)
	j.SetRiskAssessmentRequired(input.RiskAssessmentRequired)
	j.SetMaintenanceRequired(input.MaintenanceRequired)
	return j
}

func (s *SessionCreate) SetSession(input *Session) *SessionCreate {
	s.SetIdleTimeExpiredAt(input.IdleTimeExpiredAt)
	s.SetLifeTimeExpiredAt(input.LifeTimeExpiredAt)
	return s
}

func (u *UserCreate) SetUser(input *User) *UserCreate {
	u.SetEmail(input.Email)
	u.SetPassword(input.Password)
	u.SetEnabled(input.Enabled)
	return u
}
