// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/liip/sheriff"
)

func (j *Job) Marshal(options *sheriff.Options) (interface{}, error) {
	return sheriff.Marshal(options, j)
}

func (s *Session) Marshal(options *sheriff.Options) (interface{}, error) {
	return sheriff.Marshal(options, s)
}

func (u *User) Marshal(options *sheriff.Options) (interface{}, error) {
	return sheriff.Marshal(options, u)
}
